"""EcoreX deterministic release building and protected signing APIs."""

from .builder import (
    MAX_BOOTSTRAP_BYTES,
    MAX_CAPABILITY_PACK_BYTES,
    MAX_CORE_BYTES,
    SUPPORTED_TARGETS,
    ReleaseBuildError,
    ReleaseBuilder,
)
from .models import (
    ArtifactBuildInput,
    ArtifactKind,
    BuiltRelease,
    CoreDeltaBuildInput,
    ReleaseBuildSpec,
    WebBundleBuildInput,
)
from .signing import Ed25519MemorySigner, ReleaseSigner, SigningError
from .external_signer import DigestPinnedExternalSigner, ExternalSigningReceipt
from .dependency_lock import (
    DependencyLockError,
    DependencyLockManifest,
    load_dependency_lock_manifest,
)
from .candidate import (
    CandidateBuildError,
    build_candidate,
    candidate_receipt_signing_payload,
    scan_stage_tree,
    write_failure_receipt,
    write_stage_receipt,
)
from .github import (
    EnvironmentGitHubCredential,
    GitHubAssetReceipt,
    GitHubCredentialProvider,
    GitHubPublicationError,
    GitHubReleaseDraft,
    GitHubReleasePublisher,
)
from .replica import (
    EnvironmentReplicaCredential,
    HTTPSReleaseReplicaPublisher,
    ReleaseReplicaError,
    ReleaseReplicaReceipt,
    ReplicaCredentialProvider,
)
from .publication import PublishedReleaseAssets, ReleaseAssetPublicationCoordinator
from .identity import release_tag
from .public_index import (
    MAX_PUBLIC_BOOTSTRAP_INDEX_BYTES,
    PUBLIC_BOOTSTRAP_AUTHORITY_DOMAIN,
    PUBLIC_BOOTSTRAP_AUTHORITY_FUTURE_SKEW_SECONDS,
    PUBLIC_BOOTSTRAP_AUTHORITY_MAX_TTL_SECONDS,
    PUBLIC_BOOTSTRAP_FRESHNESS_DOMAIN,
    PUBLIC_BOOTSTRAP_INDEX_DOCUMENT_TYPE,
    PUBLIC_BOOTSTRAP_INDEX_FILE_NAME,
    PUBLIC_BOOTSTRAP_INDEX_SCHEMA_VERSION,
    PUBLIC_BOOTSTRAP_INDEX_TRUST,
    PublicBootstrapIndexError,
    build_public_bootstrap_index,
    public_bootstrap_authority_signing_bytes,
    public_bootstrap_freshness_signing_bytes,
    refresh_public_bootstrap_freshness,
    stable_pointer_sequence,
    unpublished_public_bootstrap_index,
    validate_public_bootstrap_index,
    write_public_bootstrap_index,
)
from .public_pointer import (
    EnvironmentPublicBootstrapCredential,
    HTTPSPublicBootstrapIndexPublisher,
    PublicBootstrapCredentialProvider,
    PublicBootstrapPublicationError,
    PublicBootstrapPublicationReceipt,
    PublicBootstrapStageReceipt,
)

__all__ = [
    "ArtifactBuildInput",
    "ArtifactKind",
    "BuiltRelease",
    "CoreDeltaBuildInput",
    "CandidateBuildError",
    "Ed25519MemorySigner",
    "DigestPinnedExternalSigner",
    "DependencyLockError",
    "DependencyLockManifest",
    "EnvironmentGitHubCredential",
    "EnvironmentReplicaCredential",
    "EnvironmentPublicBootstrapCredential",
    "ExternalSigningReceipt",
    "GitHubAssetReceipt",
    "GitHubCredentialProvider",
    "GitHubPublicationError",
    "GitHubReleaseDraft",
    "GitHubReleasePublisher",
    "release_tag",
    "HTTPSReleaseReplicaPublisher",
    "HTTPSPublicBootstrapIndexPublisher",
    "MAX_BOOTSTRAP_BYTES",
    "MAX_CAPABILITY_PACK_BYTES",
    "MAX_CORE_BYTES",
    "MAX_PUBLIC_BOOTSTRAP_INDEX_BYTES",
    "PUBLIC_BOOTSTRAP_AUTHORITY_DOMAIN",
    "PUBLIC_BOOTSTRAP_AUTHORITY_FUTURE_SKEW_SECONDS",
    "PUBLIC_BOOTSTRAP_AUTHORITY_MAX_TTL_SECONDS",
    "PUBLIC_BOOTSTRAP_FRESHNESS_DOMAIN",
    "PublishedReleaseAssets",
    "PUBLIC_BOOTSTRAP_INDEX_DOCUMENT_TYPE",
    "PUBLIC_BOOTSTRAP_INDEX_FILE_NAME",
    "PUBLIC_BOOTSTRAP_INDEX_SCHEMA_VERSION",
    "PUBLIC_BOOTSTRAP_INDEX_TRUST",
    "PublicBootstrapIndexError",
    "PublicBootstrapCredentialProvider",
    "PublicBootstrapPublicationError",
    "PublicBootstrapPublicationReceipt",
    "PublicBootstrapStageReceipt",
    "ReleaseAssetPublicationCoordinator",
    "ReleaseBuildError",
    "ReleaseBuilder",
    "ReleaseReplicaError",
    "ReleaseReplicaReceipt",
    "ReplicaCredentialProvider",
    "ReleaseBuildSpec",
    "ReleaseSigner",
    "SUPPORTED_TARGETS",
    "SigningError",
    "WebBundleBuildInput",
    "build_public_bootstrap_index",
    "public_bootstrap_authority_signing_bytes",
    "public_bootstrap_freshness_signing_bytes",
    "refresh_public_bootstrap_freshness",
    "build_candidate",
    "candidate_receipt_signing_payload",
    "load_dependency_lock_manifest",
    "scan_stage_tree",
    "stable_pointer_sequence",
    "unpublished_public_bootstrap_index",
    "validate_public_bootstrap_index",
    "write_failure_receipt",
    "write_stage_receipt",
    "write_public_bootstrap_index",
]
