"""Cloud-authoritative managed account and session leases."""

from .models import (
    LeaseSignatureError,
    LeaseValidationError,
    MAX_LEASE_DURATION,
    ManagedSessionError,
    ManagedSessionLeaseClaims,
    ManagedSessionSnapshot,
    SessionAuditRecord,
    SessionConflict,
    SessionLeaseSignature,
    SessionLogoutReceipt,
    SessionRecoveryReport,
    SessionRefreshContext,
    SessionRestartRequired,
    SessionUnavailable,
    SessionVaultError,
    SignedManagedSessionLease,
    StaleSessionRequest,
    redacted_hash,
    token_digest,
)
from .repository import (
    ActiveSessionRecord,
    ManagedSessionRepository,
    SessionInstallIntent,
    SessionStateRecord,
    StagedInstall,
    client_request_hash,
    install_request_fingerprint,
)
from .service import ManagedSessionService
from .device import (
    BrokerDeviceChallenge,
    BrokerDeviceGrant,
    BrokerPollResult,
    BrokerPollStatus,
    DeviceAuthorizationBroker,
    DeviceAuthorizationConflict,
    DeviceAuthorizationError,
    DeviceAuthorizationNotFound,
    DeviceAuthorizationSupervisor,
    DeviceAuthorizationUnavailable,
    DeviceFlowProjection,
    DeviceFlowStatus,
    ManagedDeviceAuthorizationService,
)
from .device_transport import DeviceRefreshInvalidGrant, HTTPSDeviceAuthorizationBroker
from .api import create_device_authorization_router
from .refresh import (
    ManagedSessionRefreshBroker,
    ManagedSessionRefreshRepository,
    ManagedSessionRefreshService,
    ManagedSessionRefreshSupervisor,
    SessionReauthorizationRequired,
    SessionRefreshError,
    SessionRefreshProjection,
)
from .verification import (
    Ed25519SessionLeaseVerifier,
    RejectingSessionLeaseVerifier,
    SessionLeaseVerifier,
    require_verified,
)

__all__ = [
    "ActiveSessionRecord",
    "Ed25519SessionLeaseVerifier",
    "LeaseSignatureError",
    "LeaseValidationError",
    "MAX_LEASE_DURATION",
    "ManagedSessionError",
    "ManagedSessionLeaseClaims",
    "ManagedSessionRepository",
    "ManagedSessionService",
    "ManagedSessionRefreshBroker",
    "ManagedSessionRefreshRepository",
    "ManagedSessionRefreshService",
    "ManagedSessionRefreshSupervisor",
    "ManagedDeviceAuthorizationService",
    "BrokerDeviceChallenge",
    "BrokerDeviceGrant",
    "BrokerPollResult",
    "BrokerPollStatus",
    "DeviceAuthorizationBroker",
    "DeviceAuthorizationConflict",
    "DeviceAuthorizationError",
    "DeviceAuthorizationNotFound",
    "DeviceAuthorizationSupervisor",
    "DeviceAuthorizationUnavailable",
    "DeviceFlowProjection",
    "DeviceFlowStatus",
    "DeviceRefreshInvalidGrant",
    "HTTPSDeviceAuthorizationBroker",
    "create_device_authorization_router",
    "ManagedSessionSnapshot",
    "RejectingSessionLeaseVerifier",
    "SessionAuditRecord",
    "SessionConflict",
    "SessionInstallIntent",
    "SessionLeaseSignature",
    "SessionLeaseVerifier",
    "SessionLogoutReceipt",
    "SessionRecoveryReport",
    "SessionReauthorizationRequired",
    "SessionRefreshError",
    "SessionRefreshProjection",
    "SessionRefreshContext",
    "SessionRestartRequired",
    "SessionStateRecord",
    "SessionUnavailable",
    "SessionVaultError",
    "SignedManagedSessionLease",
    "StagedInstall",
    "StaleSessionRequest",
    "client_request_hash",
    "install_request_fingerprint",
    "redacted_hash",
    "require_verified",
    "token_digest",
]
