#!/usr/bin/env python3
"""Render an approved Xiaohongshu note package to DOCX through cli-anything-wps."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


DEFAULT_WPS_ROOT = r"C:\EcoreX Artifact Desk\cli-anything-wps-master"


def load_json(path: str | None) -> dict[str, Any]:
    if not path:
        return {}
    with open(path, "r", encoding="utf-8-sig") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def slug(text: str) -> str:
    text = re.sub(r"[\\/:*?\"<>|]+", "_", text.strip())
    text = re.sub(r"\s+", "_", text)
    return text[:60] or "xhs_note"


def para(text: str, font_size: str = "11pt", bold: bool = False) -> dict[str, Any]:
    return {"type": "paragraph", "text": text, "style": {"font_size": font_size, "bold": bold}}


def heading(text: str, level: int = 1) -> dict[str, Any]:
    return {"type": "heading", "level": level, "text": text, "style": {}}


def add_image_if_exists(content: list[dict[str, Any]], path: str, name: str) -> None:
    if path and Path(path).exists():
        content.append({"type": "image_ref", "name": name, "path": str(Path(path).resolve()), "width": "10cm", "height": "15cm"})


def build_project(brief: dict[str, Any], pack: dict[str, Any], project_name: str) -> dict[str, Any]:
    now = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    brand = str(brief.get("brand", ""))
    topic = str(brief.get("selected_topic", pack.get("selected_title", "")))
    cover = pack.get("cover", {}) if isinstance(pack.get("cover"), dict) else {}

    content: list[dict[str, Any]] = [
        heading("小红书笔记交付", 1),
        para(f"品牌：{brand or '未填写'}", bold=True),
        para(f"选题：{topic or '未填写'}", bold=True),
        para(f"生成时间：{now}"),
        {"type": "page_break"},
        heading("封面与内页", 2),
    ]

    add_image_if_exists(content, str(cover.get("final_image_path", "")), "最终封面")
    for index, item in enumerate(pack.get("inner_pages", []) if isinstance(pack.get("inner_pages"), list) else [], 1):
        if isinstance(item, dict):
            add_image_if_exists(content, str(item.get("path", "")), f"内页{index}")

    content.extend(
        [
            para(f"封面主标题：{cover.get('hook', '')}"),
            para(f"封面副标题：{cover.get('subtitle', '')}"),
            heading("封面设计说明", 2),
            para(json.dumps(pack.get("cover_design", {}), ensure_ascii=False, indent=2)),
            para(f"生图状态：{json.dumps(pack.get('image_generation_status', {}), ensure_ascii=False)}"),
            heading("公式拆解", 2),
            para(json.dumps(pack.get("formula_decomposition", {}), ensure_ascii=False, indent=2)),
            heading("标题候选", 2),
            {"type": "list", "list_style": "number", "items": [str(t) for t in pack.get("titles", [])]},
            para(f"推荐标题：{pack.get('selected_title', '')}", bold=True),
            heading("正文", 2),
        ]
    )

    body = str(pack.get("body", ""))
    for block in re.split(r"\n\s*\n", body):
        if block.strip():
            content.append(para(block.strip(), font_size="11pt"))

    content.extend(
        [
            heading("TAG", 2),
            para(" ".join(str(t) for t in pack.get("tags", []))),
            heading("评论区首评", 2),
            para(str(pack.get("first_comment", ""))),
            heading("审核自检", 2),
            para(json.dumps(pack.get("audit_check", {}), ensure_ascii=False, indent=2)),
            heading("资产清单", 2),
            {"type": "list", "list_style": "bullet", "items": [str(p) for p in pack.get("asset_paths", [])]},
        ]
    )

    return {
        "version": "1.0",
        "name": project_name,
        "type": "writer",
        "settings": {
            "name": "A4 纵向",
            "page_width": "21cm",
            "page_height": "29.7cm",
            "margin_top": "2.2cm",
            "margin_bottom": "2.2cm",
            "margin_left": "2.4cm",
            "margin_right": "2.4cm",
        },
        "styles": {},
        "metadata": {
            "title": project_name,
            "author": "create-xiaohongshu-note",
            "description": "Xiaohongshu note delivery generated by Agent Skill",
            "subject": "Xiaohongshu note",
            "created": now,
            "modified": now,
            "software": "cli-anything-wps",
        },
        "content": content,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--brief", required=True)
    parser.add_argument("--note-pack", required=True)
    parser.add_argument("--output", help="Output DOCX path")
    parser.add_argument("--project-json", help="Output WPS project JSON path")
    parser.add_argument("--wps-root", default=DEFAULT_WPS_ROOT)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--overwrite", action="store_true", default=True)
    args = parser.parse_args()

    try:
        brief = load_json(args.brief)
        pack = load_json(args.note_pack)
        brand = slug(str(brief.get("brand", "brand")))
        topic = slug(str(brief.get("selected_topic", pack.get("selected_title", "topic"))))
        output = Path(args.output) if args.output else Path.cwd() / f"{time.strftime('%Y%m%d')}_{brand}_{topic}_xhs-note.docx"
        project_json = Path(args.project_json) if args.project_json else output.with_suffix(".wps-cli.json")
        project_json.parent.mkdir(parents=True, exist_ok=True)

        project = build_project(brief, pack, f"{brand}_{topic}_小红书笔记")
        project_json.write_text(json.dumps(project, ensure_ascii=False, indent=2), encoding="utf-8")

        if args.dry_run:
            print(json.dumps({"ok": True, "status": "dry_run", "project_json": str(project_json), "output": str(output)}, ensure_ascii=False))
            return 0

        wps_root = Path(args.wps_root)
        if not wps_root.exists():
            raise FileNotFoundError(f"WPS root not found: {wps_root}")

        cmd = [
            sys.executable,
            "-m",
            "cli_anything.wps",
            "--project",
            str(project_json),
            "export",
            "render",
            str(output),
            "-p",
            "docx",
            "--overwrite",
        ]
        proc = subprocess.run(cmd, cwd=str(wps_root), text=True, capture_output=True)
        result = {
            "ok": proc.returncode == 0,
            "status": "completed" if proc.returncode == 0 else "failed",
            "cmd": cmd,
            "project_json": str(project_json),
            "output": str(output),
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "returncode": proc.returncode,
        }
        print(json.dumps(result, ensure_ascii=False))
        return 0 if proc.returncode == 0 else 3
    except Exception as exc:
        print(json.dumps({"ok": False, "status": "failed", "error": str(exc)}, ensure_ascii=False))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
