"""Web route table for the EcoreX Web console.

Keep this module declarative: handler implementations live in web_channel.py
until their S8 ownership slices are moved behind dedicated modules.
"""

WEB_ROUTES = (
    '/', 'RootHandler',
    '/app', 'WebAppRootHandler',
    '/app/(.*)', 'WebAppAssetHandler',
    '/auth/login', 'AuthLoginHandler',
    '/auth/check', 'AuthCheckHandler',
    '/auth/logout', 'AuthLogoutHandler',
    '/message', 'MessageHandler',
    '/upload', 'UploadHandler',
    '/uploads/(.*)', 'UploadsHandler',
    '/api/file', 'FileServeHandler',
    '/api/voice/asr', 'VoiceAsrHandler',
    '/api/voice/tts', 'VoiceTtsHandler',
    '/poll', 'PollHandler',
    '/stream', 'StreamHandler',
    '/cancel', 'CancelHandler',
    '/api/active-requests', 'ActiveRequestsHandler',
    '/api/requests/([^/]+)/retry-prepare', 'RequestRetryPrepareHandler',
    '/api/runtime-projection', 'RuntimeProjectionHandler',
    '/api/image-jobs', 'ImageJobsHandler',
    '/api/image-jobs/([^/]+)', 'ImageJobActionHandler',
    '/api/tool-permissions', 'ToolPermissionHandler',
    '/api/update-check', 'UpdateCheckHandler',
    '/api/file-stat', 'FileStatHandler',
    '/api/file-json', 'FileJsonHandler',
    '/api/open-path', 'OpenPathHandler',
    '/api/project-folder/choose', 'ProjectFolderChooseHandler',
    '/api/project-folder', 'ProjectFolderHandler',
    '/api/extensions', 'ExtensionsHandler',
    '/api/capabilities', 'CapabilitiesHandler',
    '/api/agent-install-request', 'AgentInstallRequestHandler',
    '/api/subagents', 'SubagentsHandler',
    '/api/subagents/([^/]+)/(cancel|collect)', 'SubagentActionHandler',
    '/client', 'ClientProxyHandler',
    '/client/(.*)', 'ClientProxyHandler',
    '/chat', 'ChatHandler',
    '/config', 'ConfigHandler',
    '/api/models', 'ModelsHandler',
    '/api/channels', 'ChannelsHandler',
    '/api/external-connections', 'ExternalConnectionsHandler',
    '/api/external-connections/([^/]+)/actions', 'ExternalConnectionActionHandler',
    '/api/weixin/qrlogin', 'WeixinQrHandler',
    '/api/feishu/register', 'FeishuRegisterHandler',
    '/api/tools', 'ToolsHandler',
    '/api/skills', 'SkillsHandler',
    '/api/memory', 'MemoryHandler',
    '/api/memory/content', 'MemoryContentHandler',
    '/api/knowledge/list', 'KnowledgeListHandler',
    '/api/knowledge/read', 'KnowledgeReadHandler',
    '/api/knowledge/graph', 'KnowledgeGraphHandler',
    '/api/scheduler', 'SchedulerHandler',
    '/api/sessions', 'SessionsHandler',
    '/api/sessions/(.*)/generate_title', 'SessionTitleHandler',
    '/api/sessions/(.*)/clear_context', 'SessionClearContextHandler',
    '/api/sessions/(.*)', 'SessionDetailHandler',
    '/api/history', 'HistoryHandler',
    '/api/messages/delete', 'MessageDeleteHandler',
    '/api/ui-state', 'UiStateHandler',
    '/api/installations', 'InstallationsHandler',
    '/api/diagnostics/bundle', 'DiagnosticsBundleHandler',
    '/api/logs/snapshot', 'LogsSnapshotHandler',
    '/api/logs', 'LogsHandler',
    '/api/version', 'VersionHandler',
    '/assets/(.*)', 'AssetsHandler',
)


def route_pairs():
    """Return route path/handler pairs for tests and diagnostics."""
    return tuple(zip(WEB_ROUTES[0::2], WEB_ROUTES[1::2]))
