// Generated by tools/generate-runtime-contracts.py. DO NOT EDIT.
// Deferred Thread/Turn projection boundary; Python schemas remain authoritative.
export const GENERATED_RUNTIME_PROJECTION_CONTRACT = {
  "runtime": {
    "connectorInteractionStates": [
      "authorization_required",
      "awaiting_callback",
      "verifying",
      "reauthorization_required"
    ],
    "interactionActionStyles": [
      "primary",
      "secondary",
      "danger"
    ],
    "interactionActionTypes": [
      "submit",
      "continue",
      "cancel",
      "allow",
      "deny",
      "retry",
      "skip",
      "accept",
      "request_changes",
      "connector_begin_login",
      "connector_check_status"
    ],
    "interactionFieldControls": [
      "text",
      "textarea",
      "select",
      "checkbox"
    ],
    "interactionKinds": [
      "permission_approval",
      "information",
      "connector_login",
      "conflict_resolution",
      "artifact_review"
    ],
    "interactionStatuses": [
      "pending",
      "resolved",
      "cancelled",
      "expired"
    ],
    "itemKinds": [
      "message",
      "reasoning",
      "tool_call",
      "artifact",
      "interaction",
      "checkpoint"
    ],
    "itemStatuses": [
      "created",
      "in_progress",
      "waiting_human",
      "completed",
      "failed",
      "cancelled"
    ],
    "jobStatuses": [
      "queued",
      "leased",
      "running",
      "waiting_human",
      "retry_scheduled",
      "completed",
      "failed",
      "cancelled",
      "dead_letter"
    ],
    "threadStatuses": [
      "active",
      "archived"
    ],
    "turnStatuses": [
      "accepted",
      "queued",
      "preparing",
      "model_requested",
      "streaming",
      "tool_pending",
      "waiting_human",
      "tool_running",
      "retry_wait",
      "finalizing",
      "completed",
      "failed",
      "cancelled",
      "interrupted",
      "superseded"
    ]
  },
  "schemaSha256": "d9d1bd5c8ba36fa7d88de15606f567a29401436b686c605001cdc6a71848f8d5",
  "schemaVersion": 1,
  "wireFields": {
    "ConnectorLoginBeginResponse": {
      "ConnectorLoginBeginResponse": [
        "interaction_id",
        "connector_id",
        "state",
        "authorization_url",
        "verification_url",
        "user_code",
        "expires_at"
      ]
    },
    "ConnectorLoginCancelResponse": {
      "ConnectorLoginCancelResponse": [
        "interaction_id",
        "connector_id",
        "cancelled",
        "mutation"
      ]
    },
    "ConnectorLoginCheckResponse": {
      "ConnectorLoginCheckResponse": [
        "interaction_id",
        "connector_id",
        "connected",
        "state",
        "reason",
        "authority_refresh_revision_id",
        "mutation"
      ]
    },
    "InteractionMutationResponse": {
      "InteractionMutationResponse": [
        "interaction",
        "turn",
        "job",
        "watermark"
      ]
    },
    "InteractionProjection": {
      "InteractionProjection": [
        "interaction_id",
        "kind",
        "status",
        "prompt",
        "contract",
        "options",
        "response",
        "response_client_request_id",
        "thread_id",
        "turn_id",
        "job_id",
        "expires_at",
        "created_at",
        "updated_at"
      ]
    },
    "ItemProjection": {
      "ItemProjection": [
        "item_id",
        "thread_id",
        "turn_id",
        "kind",
        "status",
        "content",
        "inherited",
        "created_at",
        "updated_at"
      ]
    },
    "JobProjection": {
      "JobProjection": [
        "job_id",
        "kind",
        "status",
        "priority",
        "attempt",
        "max_attempts",
        "thread_id",
        "turn_id",
        "available_at",
        "deadline",
        "reason_code",
        "created_at",
        "updated_at"
      ]
    },
    "ReplaceTurnResponse": {
      "ReplaceTurnResponse": [
        "superseded_turn",
        "replacement_turn",
        "job",
        "watermark"
      ]
    },
    "ThreadListResponse": {
      "ThreadListResponse": [
        "items",
        "next_cursor"
      ]
    },
    "ThreadProjection": {
      "ThreadProjection": [
        "thread_id",
        "status",
        "title",
        "pinned",
        "active_turn_status",
        "metadata",
        "forked_from_thread_id",
        "forked_from_turn_id",
        "forked_from_seq",
        "created_at",
        "updated_at"
      ]
    },
    "ThreadProjectionResponse": {
      "InteractionAction": [
        "action_id",
        "label",
        "action_type",
        "style",
        "submits_form"
      ],
      "InteractionChoice": [
        "option_id",
        "label",
        "description"
      ],
      "InteractionConnectorContext": [
        "connector_id",
        "display_name",
        "state",
        "required_action_ids"
      ],
      "InteractionContract": [
        "schema_version",
        "title",
        "fields",
        "actions",
        "connector"
      ],
      "InteractionFormField": [
        "field_id",
        "label",
        "control",
        "required",
        "description",
        "placeholder",
        "min_length",
        "max_length",
        "options",
        "sensitive"
      ],
      "InteractionProjection": [
        "interaction_id",
        "kind",
        "status",
        "prompt",
        "contract",
        "options",
        "response",
        "response_client_request_id",
        "thread_id",
        "turn_id",
        "job_id",
        "expires_at",
        "created_at",
        "updated_at"
      ],
      "InteractionResponse": [
        "action_id",
        "values"
      ],
      "ItemProjection": [
        "item_id",
        "thread_id",
        "turn_id",
        "kind",
        "status",
        "content",
        "inherited",
        "created_at",
        "updated_at"
      ],
      "JobProjection": [
        "job_id",
        "kind",
        "status",
        "priority",
        "attempt",
        "max_attempts",
        "thread_id",
        "turn_id",
        "available_at",
        "deadline",
        "reason_code",
        "created_at",
        "updated_at"
      ],
      "ThreadProjection": [
        "thread_id",
        "status",
        "title",
        "pinned",
        "active_turn_status",
        "metadata",
        "forked_from_thread_id",
        "forked_from_turn_id",
        "forked_from_seq",
        "created_at",
        "updated_at"
      ],
      "ThreadProjectionResponse": [
        "thread",
        "turns",
        "items",
        "jobs",
        "interactions",
        "watermark"
      ],
      "TurnProjection": [
        "turn_id",
        "thread_id",
        "status",
        "input",
        "agent_model_id",
        "image_model_id",
        "client_message_id",
        "metadata",
        "inherited",
        "terminal_reason",
        "created_at",
        "updated_at"
      ]
    },
    "TurnMutationResponse": {
      "TurnMutationResponse": [
        "turn",
        "job",
        "watermark"
      ]
    },
    "TurnProjection": {
      "TurnProjection": [
        "turn_id",
        "thread_id",
        "status",
        "input",
        "agent_model_id",
        "image_model_id",
        "client_message_id",
        "metadata",
        "inherited",
        "terminal_reason",
        "created_at",
        "updated_at"
      ]
    }
  }
} as const;
export type GeneratedRuntimeProjectionContractName = keyof typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.wireFields;
export type GeneratedThreadStatus = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.threadStatuses[number];
export type GeneratedTurnStatus = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.turnStatuses[number];
export type GeneratedItemKind = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.itemKinds[number];
export type GeneratedItemStatus = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.itemStatuses[number];
export type GeneratedJobStatus = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.jobStatuses[number];
export type GeneratedInteractionKind = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.interactionKinds[number];
export type GeneratedInteractionStatus = typeof GENERATED_RUNTIME_PROJECTION_CONTRACT.runtime.interactionStatuses[number];
