// Generated by tools/generate-runtime-contracts.py. DO NOT EDIT.
// Progressively loaded Settings boundary; Python schemas remain authoritative.
export const GENERATED_SETTINGS_RUNTIME_CONTRACT = {
  "schemaSha256": "e2614b327b5b9513ccb28ce37a7c264db37b76c58505f93c4939854b77a281d1",
  "schemaVersion": 1,
  "values": {
    "memoryResetStatuses": [
      "active",
      "undone",
      "purged"
    ],
    "migrationCredentialKinds": [
      "api_key",
      "refresh_token",
      "access_token",
      "password",
      "cryptographic_key",
      "client_secret",
      "credential"
    ],
    "migrationCredentialOrigins": [
      "product_configuration",
      "mcp_configuration",
      "skill_configuration",
      "permission_configuration"
    ],
    "migrationQuarantineStatuses": [
      "absent",
      "available",
      "deleted"
    ],
    "outputLocationAliases": [
      "documents",
      "downloads",
      "workspace"
    ],
    "outputMaterializationStatuses": [
      "preparing",
      "published",
      "completed"
    ],
    "systemHealthStatuses": [
      "healthy",
      "degraded",
      "attention",
      "critical"
    ]
  },
  "wireFields": {
    "MemoryMutationResponse": {
      "MemoryMutationResponse": [
        "memory",
        "reset"
      ],
      "MemoryResetProjectionResponse": [
        "reset_id",
        "status",
        "affected_records",
        "affected_files",
        "created_at",
        "undo_until",
        "updated_at",
        "can_undo"
      ],
      "MemorySnapshotResponse": [
        "revision",
        "active_learned_records",
        "active_user_files",
        "factory_records",
        "tombstoned_records",
        "tombstoned_files",
        "resettable_count",
        "latest_reset"
      ]
    },
    "MemorySnapshotResponse": {
      "MemoryResetProjectionResponse": [
        "reset_id",
        "status",
        "affected_records",
        "affected_files",
        "created_at",
        "undo_until",
        "updated_at",
        "can_undo"
      ],
      "MemorySnapshotResponse": [
        "revision",
        "active_learned_records",
        "active_user_files",
        "factory_records",
        "tombstoned_records",
        "tombstoned_files",
        "resettable_count",
        "latest_reset"
      ]
    },
    "MigrationQuarantineResponse": {
      "MigrationQuarantineItemResponse": [
        "kind",
        "origin",
        "count"
      ],
      "MigrationQuarantineResponse": [
        "status",
        "entry_count",
        "can_delete",
        "deleted_at",
        "items"
      ]
    },
    "OutputLocationCatalogResponse": {
      "OutputLocationCatalogResponse": [
        "items"
      ],
      "OutputLocationOptionResponse": [
        "alias",
        "available"
      ]
    },
    "OutputMaterializationResponse": {
      "OutputMaterializationResponse": [
        "materialization_id",
        "artifact_id",
        "revision_id",
        "output_policy_snapshot_id",
        "location_alias",
        "display_name",
        "sha256",
        "size_bytes",
        "status",
        "reused_existing",
        "created_at",
        "completed_at"
      ]
    },
    "OutputPreferenceResponse": {
      "OutputPreferenceResponse": [
        "account_id",
        "location_alias",
        "revision",
        "output_policy_snapshot_id",
        "updated_at"
      ]
    },
    "SystemHealthPublicResponse": {
      "SystemHealthComponentResponse": [
        "component_id",
        "label",
        "status",
        "message"
      ],
      "SystemHealthPublicResponse": [
        "sample_id",
        "overall",
        "summary",
        "components",
        "sampled_at"
      ]
    },
    "SystemHealthTechnicalResponse": {
      "SystemHealthComponentResponse": [
        "component_id",
        "label",
        "status",
        "message"
      ],
      "SystemHealthTechnicalResponse": [
        "sample_id",
        "overall",
        "summary",
        "components",
        "sampled_at",
        "metrics"
      ]
    },
    "SystemMetricHistoryResponse": {
      "SystemHealthComponentResponse": [
        "component_id",
        "label",
        "status",
        "message"
      ],
      "SystemHealthTechnicalResponse": [
        "sample_id",
        "overall",
        "summary",
        "components",
        "sampled_at",
        "metrics"
      ],
      "SystemMetricHistoryResponse": [
        "items"
      ]
    }
  }
} as const;
export type GeneratedMemoryResetStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.memoryResetStatuses[number];
export type GeneratedMigrationCredentialKind = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.migrationCredentialKinds[number];
export type GeneratedMigrationCredentialOrigin = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.migrationCredentialOrigins[number];
export type GeneratedMigrationQuarantineStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.migrationQuarantineStatuses[number];
export type GeneratedOutputLocationAlias = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.outputLocationAliases[number];
export type GeneratedOutputMaterializationStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.outputMaterializationStatuses[number];
export type GeneratedSystemHealthStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.systemHealthStatuses[number];
