// Generated by tools/generate-runtime-contracts.py. DO NOT EDIT.
// Progressively loaded Artifact boundary; Python schemas remain authoritative.
export const GENERATED_ARTIFACT_RUNTIME_CONTRACT = {
  "schemaSha256": "2f9311b90ed0141f123c43a12bc2fb549d10a5a33a2d7b1d0a724cc3360fa340",
  "schemaVersion": 1,
  "values": {
    "annotationKinds": [
      "rectangle",
      "ellipse",
      "point",
      "polygon",
      "polyline",
      "brush"
    ],
    "coordinateSpaceVersion": "oriented-normalized-v1",
    "retouchJobStatuses": [
      "queued",
      "running",
      "completed",
      "failed",
      "cancelled"
    ],
    "retouchViewTools": [
      "rectangle",
      "ellipse",
      "point",
      "polygon",
      "polyline",
      "brush",
      "select",
      "pan"
    ],
    "retouchWorkspaceStatuses": [
      "editing",
      "submitting",
      "submitted"
    ]
  },
  "wireFields": {
    "ArtifactExternalActionResponse": {
      "ArtifactExternalActionResponse": [
        "artifact_id",
        "revision_id",
        "action",
        "client_request_id",
        "status",
        "requested_at",
        "updated_at",
        "failure_code"
      ]
    },
    "ArtifactListResponse": {
      "ArtifactLineageResponse": [
        "source_artifact_ids",
        "supersedes_revision_id"
      ],
      "ArtifactListResponse": [
        "items",
        "count"
      ],
      "ArtifactProjectionResponse": [
        "artifact_id",
        "revision_id",
        "family",
        "role",
        "visibility",
        "status",
        "display_name",
        "mime_type",
        "size_bytes",
        "sha256",
        "created_at",
        "lineage",
        "renditions",
        "actions",
        "feedback",
        "quality_evidence"
      ],
      "FeedbackProjectionResponse": [
        "feedback_id",
        "revision_id",
        "signal",
        "recorded_at"
      ],
      "QualityCheckResponse": [
        "name",
        "status",
        "detail"
      ],
      "QualityEvidenceResponse": [
        "status",
        "checks",
        "score",
        "summary"
      ],
      "RenditionProjectionResponse": [
        "kind",
        "mime_type",
        "size_bytes",
        "sha256"
      ]
    },
    "ArtifactProjectionResponse": {
      "ArtifactLineageResponse": [
        "source_artifact_ids",
        "supersedes_revision_id"
      ],
      "ArtifactProjectionResponse": [
        "artifact_id",
        "revision_id",
        "family",
        "role",
        "visibility",
        "status",
        "display_name",
        "mime_type",
        "size_bytes",
        "sha256",
        "created_at",
        "lineage",
        "renditions",
        "actions",
        "feedback",
        "quality_evidence"
      ],
      "FeedbackProjectionResponse": [
        "feedback_id",
        "revision_id",
        "signal",
        "recorded_at"
      ],
      "QualityCheckResponse": [
        "name",
        "status",
        "detail"
      ],
      "QualityEvidenceResponse": [
        "status",
        "checks",
        "score",
        "summary"
      ],
      "RenditionProjectionResponse": [
        "kind",
        "mime_type",
        "size_bytes",
        "sha256"
      ]
    },
    "FeedbackProjectionResponse": {
      "FeedbackProjectionResponse": [
        "feedback_id",
        "revision_id",
        "signal",
        "recorded_at"
      ]
    },
    "RetouchJobResponse": {
      "RetouchAnnotationResponse": [
        "kind",
        "normalized_geometry",
        "instruction",
        "annotation_id"
      ],
      "RetouchEditSurfaceResponse": [
        "base_revision_id",
        "raster_digest",
        "width_px",
        "height_px",
        "orientation",
        "color_space",
        "mime_type",
        "coordinate_space_version"
      ],
      "RetouchInspectionRegionResponse": [
        "normalized_geometry",
        "summary"
      ],
      "RetouchJobResponse": [
        "job_id",
        "artifact_id",
        "base_revision_id",
        "request",
        "status",
        "created_at",
        "result_revision_id",
        "change_summary",
        "inspection_regions",
        "failure_reason"
      ],
      "RetouchMaskResponse": [
        "schema_version",
        "coordinate_space_version",
        "width_px",
        "height_px",
        "sha256",
        "size_bytes",
        "covered_fraction",
        "pixel_regions"
      ],
      "RetouchPixelRegionResponse": [
        "x",
        "y",
        "width",
        "height"
      ],
      "RetouchRequestResponse": [
        "base_revision_id",
        "selected_artifact_ids",
        "agent_model_id",
        "image_model_id",
        "annotations",
        "reference_artifact_ids",
        "global_instruction",
        "client_request_id",
        "pinned_reference_revision_ids",
        "edit_surface",
        "mask"
      ]
    },
    "RetouchWorkspaceResponse": {
      "ArtifactLineageResponse": [
        "source_artifact_ids",
        "supersedes_revision_id"
      ],
      "ArtifactProjectionResponse": [
        "artifact_id",
        "revision_id",
        "family",
        "role",
        "visibility",
        "status",
        "display_name",
        "mime_type",
        "size_bytes",
        "sha256",
        "created_at",
        "lineage",
        "renditions",
        "actions",
        "feedback",
        "quality_evidence"
      ],
      "FeedbackProjectionResponse": [
        "feedback_id",
        "revision_id",
        "signal",
        "recorded_at"
      ],
      "QualityCheckResponse": [
        "name",
        "status",
        "detail"
      ],
      "QualityEvidenceResponse": [
        "status",
        "checks",
        "score",
        "summary"
      ],
      "RenditionProjectionResponse": [
        "kind",
        "mime_type",
        "size_bytes",
        "sha256"
      ],
      "RetouchAnnotationResponse": [
        "kind",
        "normalized_geometry",
        "instruction",
        "annotation_id"
      ],
      "RetouchEditSurfaceResponse": [
        "base_revision_id",
        "raster_digest",
        "width_px",
        "height_px",
        "orientation",
        "color_space",
        "mime_type",
        "coordinate_space_version"
      ],
      "RetouchInspectionRegionResponse": [
        "normalized_geometry",
        "summary"
      ],
      "RetouchJobResponse": [
        "job_id",
        "artifact_id",
        "base_revision_id",
        "request",
        "status",
        "created_at",
        "result_revision_id",
        "change_summary",
        "inspection_regions",
        "failure_reason"
      ],
      "RetouchMaskResponse": [
        "schema_version",
        "coordinate_space_version",
        "width_px",
        "height_px",
        "sha256",
        "size_bytes",
        "covered_fraction",
        "pixel_regions"
      ],
      "RetouchPixelRegionResponse": [
        "x",
        "y",
        "width",
        "height"
      ],
      "RetouchReferenceResponse": [
        "artifact_id",
        "revision_id",
        "display_name",
        "mime_type",
        "sha256",
        "preview_url"
      ],
      "RetouchRequestResponse": [
        "base_revision_id",
        "selected_artifact_ids",
        "agent_model_id",
        "image_model_id",
        "annotations",
        "reference_artifact_ids",
        "global_instruction",
        "client_request_id",
        "pinned_reference_revision_ids",
        "edit_surface",
        "mask"
      ],
      "RetouchViewStateResponse": [
        "zoom",
        "pan_x",
        "pan_y",
        "selected_annotation_id",
        "tool"
      ],
      "RetouchWorkspaceResponse": [
        "workspace_id",
        "artifact_id",
        "version",
        "status",
        "edit_surface",
        "annotations",
        "references",
        "global_instruction",
        "view_state",
        "mask",
        "submitted_job_id",
        "job",
        "result",
        "result_surface",
        "surface_url",
        "result_url",
        "created_at",
        "updated_at"
      ]
    }
  }
} as const;
export type GeneratedArtifactContractName = keyof typeof GENERATED_ARTIFACT_RUNTIME_CONTRACT.wireFields;
export type GeneratedRetouchAnnotationKind = typeof GENERATED_ARTIFACT_RUNTIME_CONTRACT.values.annotationKinds[number];
export type GeneratedRetouchJobStatus = typeof GENERATED_ARTIFACT_RUNTIME_CONTRACT.values.retouchJobStatuses[number];
export type GeneratedRetouchViewTool = typeof GENERATED_ARTIFACT_RUNTIME_CONTRACT.values.retouchViewTools[number];
export type GeneratedRetouchWorkspaceStatus = typeof GENERATED_ARTIFACT_RUNTIME_CONTRACT.values.retouchWorkspaceStatuses[number];
