// Generated by tools/generate-runtime-contracts.py. DO NOT EDIT.
// Progressively loaded Settings boundary; Python schemas remain authoritative.
export const GENERATED_SETTINGS_RUNTIME_CONTRACT = {
  "schemaSha256": "f979c63c2fd7b77b84dbf905b7f89f46f81bd2e177abe14ec42e0f8cad820cc7",
  "schemaVersion": 1,
  "values": {
    "knowledgeNodeKinds": [
      "category",
      "document"
    ],
    "memoryContentKinds": [
      "file",
      "evolution"
    ],
    "memoryContentOrigins": [
      "factory",
      "learned",
      "imported"
    ],
    "memoryContentViews": [
      "files",
      "evolution"
    ],
    "memoryResetStatuses": [
      "active",
      "undone",
      "purged"
    ],
    "migrationCredentialKinds": [
      "api_key",
      "refresh_token",
      "access_token",
      "password",
      "cryptographic_key",
      "client_secret",
      "credential"
    ],
    "migrationCredentialOrigins": [
      "product_configuration",
      "mcp_configuration",
      "skill_configuration",
      "permission_configuration"
    ],
    "migrationQuarantineStatuses": [
      "absent",
      "available",
      "deleted"
    ],
    "outputLocationAliases": [
      "documents",
      "downloads",
      "workspace"
    ],
    "outputMaterializationStatuses": [
      "preparing",
      "published",
      "completed"
    ],
    "systemHealthStatuses": [
      "healthy",
      "degraded",
      "attention",
      "critical"
    ]
  },
  "wireFields": {
    "KnowledgeDocumentResponse": {
      "KnowledgeDocumentResponse": [
        "path",
        "name",
        "content",
        "size_bytes",
        "updated_at",
        "links"
      ]
    },
    "KnowledgeGraphResponse": {
      "KnowledgeGraphEdgeResponse": [
        "source",
        "target"
      ],
      "KnowledgeGraphNodeResponse": [
        "path",
        "label"
      ],
      "KnowledgeGraphResponse": [
        "nodes",
        "edges"
      ]
    },
    "KnowledgeImportResponse": {
      "KnowledgeImportItemResponse": [
        "original_name",
        "name",
        "path",
        "status",
        "reason"
      ],
      "KnowledgeImportResponse": [
        "imported_count",
        "rejected_count",
        "total_bytes",
        "items"
      ]
    },
    "KnowledgeTreeResponse": {
      "KnowledgeNodeResponse": [
        "path",
        "name",
        "kind",
        "size_bytes",
        "updated_at",
        "children"
      ],
      "KnowledgeTreeResponse": [
        "root",
        "query",
        "items"
      ]
    },
    "MemoryContentDocumentResponse": {
      "MemoryContentDocumentResponse": [
        "item_id",
        "name",
        "path",
        "kind",
        "origin",
        "source",
        "size_bytes",
        "updated_at",
        "content"
      ]
    },
    "MemoryContentPageResponse": {
      "MemoryContentItemResponse": [
        "item_id",
        "name",
        "path",
        "kind",
        "origin",
        "source",
        "size_bytes",
        "updated_at"
      ],
      "MemoryContentPageResponse": [
        "view",
        "page",
        "page_size",
        "total",
        "items"
      ]
    },
    "MemoryMutationResponse": {
      "MemoryMutationResponse": [
        "memory",
        "reset"
      ],
      "MemoryResetProjectionResponse": [
        "reset_id",
        "status",
        "affected_records",
        "affected_files",
        "created_at",
        "undo_until",
        "updated_at",
        "can_undo"
      ],
      "MemorySnapshotResponse": [
        "revision",
        "active_learned_records",
        "active_user_files",
        "factory_records",
        "tombstoned_records",
        "tombstoned_files",
        "resettable_count",
        "latest_reset"
      ]
    },
    "MemorySnapshotResponse": {
      "MemoryResetProjectionResponse": [
        "reset_id",
        "status",
        "affected_records",
        "affected_files",
        "created_at",
        "undo_until",
        "updated_at",
        "can_undo"
      ],
      "MemorySnapshotResponse": [
        "revision",
        "active_learned_records",
        "active_user_files",
        "factory_records",
        "tombstoned_records",
        "tombstoned_files",
        "resettable_count",
        "latest_reset"
      ]
    },
    "MigrationQuarantineResponse": {
      "MigrationQuarantineItemResponse": [
        "kind",
        "origin",
        "count"
      ],
      "MigrationQuarantineResponse": [
        "status",
        "entry_count",
        "can_delete",
        "deleted_at",
        "items"
      ]
    },
    "OutputLocationCatalogResponse": {
      "OutputLocationCatalogResponse": [
        "items"
      ],
      "OutputLocationOptionResponse": [
        "alias",
        "available"
      ]
    },
    "OutputMaterializationResponse": {
      "OutputMaterializationResponse": [
        "materialization_id",
        "artifact_id",
        "revision_id",
        "output_policy_snapshot_id",
        "location_alias",
        "display_name",
        "sha256",
        "size_bytes",
        "status",
        "reused_existing",
        "created_at",
        "completed_at"
      ]
    },
    "OutputPreferenceResponse": {
      "OutputPreferenceResponse": [
        "account_id",
        "location_alias",
        "revision",
        "output_policy_snapshot_id",
        "updated_at"
      ]
    },
    "SystemHealthPublicResponse": {
      "SystemHealthComponentResponse": [
        "component_id",
        "label",
        "status",
        "message"
      ],
      "SystemHealthPublicResponse": [
        "sample_id",
        "overall",
        "summary",
        "components",
        "sampled_at"
      ]
    },
    "SystemHealthTechnicalResponse": {
      "SystemHealthComponentResponse": [
        "component_id",
        "label",
        "status",
        "message"
      ],
      "SystemHealthTechnicalResponse": [
        "sample_id",
        "overall",
        "summary",
        "components",
        "sampled_at",
        "metrics"
      ]
    },
    "SystemMetricHistoryResponse": {
      "SystemHealthComponentResponse": [
        "component_id",
        "label",
        "status",
        "message"
      ],
      "SystemHealthTechnicalResponse": [
        "sample_id",
        "overall",
        "summary",
        "components",
        "sampled_at",
        "metrics"
      ],
      "SystemMetricHistoryResponse": [
        "items"
      ]
    }
  }
} as const;
export type GeneratedMemoryResetStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.memoryResetStatuses[number];
export type GeneratedMemoryContentKind = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.memoryContentKinds[number];
export type GeneratedMemoryContentOrigin = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.memoryContentOrigins[number];
export type GeneratedMemoryContentView = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.memoryContentViews[number];
export type GeneratedKnowledgeNodeKind = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.knowledgeNodeKinds[number];
export type GeneratedMigrationCredentialKind = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.migrationCredentialKinds[number];
export type GeneratedMigrationCredentialOrigin = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.migrationCredentialOrigins[number];
export type GeneratedMigrationQuarantineStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.migrationQuarantineStatuses[number];
export type GeneratedOutputLocationAlias = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.outputLocationAliases[number];
export type GeneratedOutputMaterializationStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.outputMaterializationStatuses[number];
export type GeneratedSystemHealthStatus = typeof GENERATED_SETTINGS_RUNTIME_CONTRACT.values.systemHealthStatuses[number];
