// Generated by tools/generate-runtime-contracts.py. DO NOT EDIT.
// Source of truth: authoritative Python protocol/domain schemas.
export const GENERATED_RUNTIME_CONTRACT = {
  "artifact": {
    "actions": [
      "preview",
      "open",
      "download",
      "reveal",
      "feedback",
      "precise_retouch"
    ],
    "families": [
      "document",
      "spreadsheet",
      "presentation",
      "pdf",
      "image",
      "audio",
      "video",
      "data_export",
      "web_report",
      "archive",
      "cloud_link"
    ],
    "feedbackSignals": [
      "thumbs_up",
      "thumbs_down"
    ],
    "qualityStatuses": [
      "not_checked",
      "passed",
      "warning",
      "failed"
    ],
    "renditionKinds": [
      "preview",
      "thumbnail"
    ],
    "roles": [
      "deliverable",
      "rendition",
      "source",
      "intermediate",
      "diagnostic"
    ],
    "statuses": [
      "pending",
      "ready",
      "failed",
      "deleted"
    ],
    "visibilities": [
      "primary",
      "secondary"
    ]
  },
  "bootstrap": {
    "connectorHealth": [
      "connected",
      "disconnected",
      "degraded",
      "unconfigured"
    ],
    "connectorTiers": [
      "stable",
      "beta"
    ],
    "extensionActionIds": [
      "enable",
      "disable",
      "health_check",
      "rollback",
      "configure",
      "uninstall"
    ],
    "extensionCategories": [
      "system",
      "office",
      "image_media",
      "collaboration",
      "data",
      "development",
      "automation",
      "general"
    ],
    "extensionExportKinds": [
      "tool",
      "skill",
      "mcp_server",
      "connector",
      "capability_pack"
    ],
    "extensionExposures": [
      "direct",
      "deferred",
      "hidden"
    ],
    "extensionHealth": [
      "unknown",
      "healthy",
      "degraded",
      "unhealthy",
      "circuit_open"
    ],
    "extensionKinds": [
      "skill",
      "mcp_server",
      "tool_provider",
      "connector_provider",
      "capability_pack"
    ],
    "extensionSources": [
      "core_bundle",
      "signed_release",
      "capability_pack",
      "administrator",
      "local_bundle",
      "legacy_import"
    ],
    "extensionStatuses": [
      "staged",
      "enabled",
      "disabled",
      "quarantined",
      "uninstalled"
    ],
    "extensionTrust": [
      "builtin",
      "administrator",
      "verified_publisher",
      "local_untrusted"
    ],
    "modelServiceStates": [
      "ready",
      "unavailable"
    ],
    "permissionApprovals": [
      "on-request",
      "never"
    ],
    "permissionProfiles": [
      "default",
      "full_access"
    ],
    "permissionSandboxes": [
      "workspace-write",
      "danger-full-access"
    ],
    "updateStates": [
      "idle",
      "available",
      "downloading",
      "awaiting_user",
      "activating",
      "failed"
    ]
  },
  "schemaSha256": "5fa103fc0e57972d6e12aaf0c917ccf1f9b552ff4cb7cc87f882a985dc5cb183",
  "schemaVersion": 1,
  "versions": {
    "api": "v1",
    "eventEnvelope": 1,
    "eventSchema": 1,
    "extensionContract": "1.0",
    "storageSchema": 1
  },
  "wireFields": {
    "ArtifactProjection": {
      "ArtifactLineage": [
        "source_artifact_ids",
        "supersedes_revision_id"
      ],
      "ArtifactProjection": [
        "artifact_id",
        "revision_id",
        "family",
        "role",
        "visibility",
        "status",
        "display_name",
        "mime_type",
        "size_bytes",
        "sha256",
        "created_at",
        "lineage",
        "renditions",
        "actions",
        "feedback",
        "quality_evidence"
      ],
      "FeedbackProjection": [
        "feedback_id",
        "revision_id",
        "signal",
        "recorded_at"
      ],
      "QualityCheck": [
        "name",
        "status",
        "detail"
      ],
      "QualityEvidence": [
        "status",
        "checks",
        "score",
        "summary"
      ],
      "RenditionProjection": [
        "kind",
        "mime_type",
        "size_bytes",
        "sha256"
      ]
    },
    "BootstrapResponse": {
      "BootstrapResponse": [
        "api_version",
        "event_schema_version",
        "storage_schema_version",
        "login",
        "policy_lease",
        "models",
        "model_service",
        "login_service",
        "share_service",
        "retouch_service",
        "quota",
        "permissions",
        "connectors",
        "extensions",
        "update",
        "csrf_token",
        "server_time"
      ]
    },
    "ConversationUsageProjection": {
      "ConversationUsageProjection": [
        "thread_id",
        "timezone",
        "scope",
        "source",
        "complete_across_devices",
        "today",
        "week",
        "context",
        "task_activity",
        "calculated_at"
      ]
    },
    "CreateTurnRequest": {
      "CreateTurnRequest": [
        "input",
        "agent_model_id",
        "image_model_id",
        "explicit_tool_ids",
        "attachment_ids",
        "client_message_id",
        "metadata"
      ]
    },
    "EventEnvelope": {
      "EventEnvelope": [
        "schema_version",
        "event_id",
        "seq",
        "thread_id",
        "turn_id",
        "item_id",
        "job_id",
        "tool_call_id",
        "client_message_id",
        "causation_id",
        "correlation_id",
        "trace_id",
        "config_snapshot_id",
        "capability_snapshot_id",
        "permission_snapshot_id",
        "extension_snapshot_id",
        "event_type",
        "created_at",
        "payload"
      ]
    },
    "InputAttachmentProjection": {
      "InputAttachmentProjection": [
        "attachment_id",
        "revision_id",
        "display_name",
        "mime_type",
        "size_bytes",
        "media_kind",
        "sha256",
        "thumbnail_url",
        "created_at"
      ]
    },
    "ProjectListResponse": {
      "ProjectListResponse": [
        "projects"
      ]
    },
    "QueueTurnRequest": {
      "QueueTurnRequest": [
        "input",
        "agent_model_id",
        "image_model_id",
        "explicit_tool_ids",
        "attachment_ids",
        "client_message_id",
        "metadata"
      ]
    },
    "ReplaceTurnRequest": {
      "ReplaceTurnRequest": [
        "input",
        "agent_model_id",
        "image_model_id",
        "explicit_tool_ids",
        "attachment_ids",
        "client_message_id",
        "metadata",
        "reason"
      ]
    },
    "RetouchBody": {
      "RetouchBody": [
        "base_revision_id",
        "selected_artifact_ids",
        "agent_model_id",
        "image_model_id",
        "annotations",
        "reference_artifact_ids",
        "global_instruction",
        "client_request_id"
      ]
    },
    "RetouchWorkspaceSubmitBody": {
      "RetouchWorkspaceSubmitBody": [
        "expected_version",
        "agent_model_id",
        "image_model_id",
        "client_request_id"
      ]
    },
    "SteerTurnRequest": {
      "SteerTurnRequest": [
        "input",
        "agent_model_id",
        "image_model_id",
        "explicit_tool_ids",
        "attachment_ids",
        "client_message_id",
        "metadata"
      ]
    }
  }
} as const;
export type GeneratedArtifactAction = typeof GENERATED_RUNTIME_CONTRACT.artifact.actions[number];
export type GeneratedArtifactFamily = typeof GENERATED_RUNTIME_CONTRACT.artifact.families[number];
export type GeneratedArtifactRole = typeof GENERATED_RUNTIME_CONTRACT.artifact.roles[number];
export type GeneratedArtifactStatus = typeof GENERATED_RUNTIME_CONTRACT.artifact.statuses[number];
export type GeneratedArtifactVisibility = typeof GENERATED_RUNTIME_CONTRACT.artifact.visibilities[number];
export type GeneratedQualityStatus = typeof GENERATED_RUNTIME_CONTRACT.artifact.qualityStatuses[number];
export type GeneratedRenditionKind = typeof GENERATED_RUNTIME_CONTRACT.artifact.renditionKinds[number];
