"""EcoreX v1 office artifact domain.

Only this package classifies user deliverables.  UI clients must render the
returned projection and must not infer visibility from paths or extensions.
"""

from .classification import (
    ArtifactClassifier,
    ClassificationDecision,
    EXPLICIT_DELIVERABLE_EXTENSIONS,
    INTERNAL_ARTIFACT_FAMILIES,
    INTERNAL_ARTIFACT_ROLES,
    PUBLIC_ARTIFACT_FAMILIES,
    PUBLIC_ARTIFACT_VISIBILITIES,
    SOURCE_CODE_EXTENSIONS,
)
from .errors import (
    ArtifactActionOutcomeUnknown,
    ArtifactActionUnavailable,
    ArtifactConflict,
    ArtifactError,
    ArtifactExportFailed,
    ArtifactLaunchFailed,
    ArtifactNotFound,
    ArtifactNotUserVisible,
    ContentIntegrityError,
    IdempotencyConflict,
    RetouchConflict,
    RevisionNotFound,
)
from .identity import (
    minute_display_name,
    new_artifact_id,
    new_revision_id,
    sanitize_display_filename,
)
from .models import (
    ArtifactAction,
    ArtifactExternalActionReceipt,
    ArtifactExternalActionStatus,
    ArtifactFamily,
    ArtifactLineage,
    ArtifactProjection,
    ArtifactRole,
    ArtifactScope,
    ArtifactStatus,
    ArtifactVisibility,
    FeedbackProjection,
    FeedbackRecord,
    FeedbackRequest,
    FeedbackSignal,
    InspectionRegion,
    QualityCheck,
    QualityEvidence,
    QualityStatus,
    RenditionKind,
    RenditionProjection,
    RetouchAnnotation,
    RetouchExecutionBinding,
    RetouchJob,
    RetouchJobProjection,
    RetouchJobStatus,
    RetouchRequest,
    RetouchResult,
    RetouchStagedResult,
)
from .repository import ArtifactRepository
from .service import ArtifactService, TrustedDeliverableDeclaration
from .storage import ContentAddressedStore, StoredBlob
from .retouch_workspace import (
    MAX_RETOUCH_REFERENCES,
    RetouchEditSurface,
    RetouchReference,
    RetouchWorkspaceProjection,
    RetouchWorkspaceStatus,
)
from .actions import (
    ArtifactActionExecutor,
    ArtifactExportMaterializer,
    ArtifactLauncher,
    ArtifactLaunchTarget,
    PreparedArtifactAction,
    SystemArtifactLauncher,
)

__all__ = [
    "ArtifactAction",
    "ArtifactActionExecutor",
    "ArtifactActionOutcomeUnknown",
    "ArtifactActionUnavailable",
    "ArtifactExternalActionReceipt",
    "ArtifactExternalActionStatus",
    "ArtifactExportFailed",
    "ArtifactExportMaterializer",
    "ArtifactLauncher",
    "ArtifactLaunchFailed",
    "ArtifactLaunchTarget",
    "ArtifactClassifier",
    "ArtifactConflict",
    "ArtifactError",
    "ArtifactFamily",
    "ArtifactLineage",
    "ArtifactNotFound",
    "ArtifactNotUserVisible",
    "ArtifactProjection",
    "ArtifactRepository",
    "ArtifactRole",
    "ArtifactScope",
    "ArtifactService",
    "ArtifactStatus",
    "ArtifactVisibility",
    "ClassificationDecision",
    "ContentAddressedStore",
    "ContentIntegrityError",
    "EXPLICIT_DELIVERABLE_EXTENSIONS",
    "FeedbackProjection",
    "FeedbackRecord",
    "FeedbackRequest",
    "FeedbackSignal",
    "IdempotencyConflict",
    "INTERNAL_ARTIFACT_FAMILIES",
    "INTERNAL_ARTIFACT_ROLES",
    "InspectionRegion",
    "QualityCheck",
    "QualityEvidence",
    "QualityStatus",
    "PUBLIC_ARTIFACT_FAMILIES",
    "PUBLIC_ARTIFACT_VISIBILITIES",
    "RenditionKind",
    "RenditionProjection",
    "RetouchAnnotation",
    "RetouchConflict",
    "RetouchExecutionBinding",
    "RetouchEditSurface",
    "RetouchJob",
    "RetouchJobProjection",
    "RetouchJobStatus",
    "RetouchReference",
    "RetouchRequest",
    "RetouchResult",
    "RetouchStagedResult",
    "RetouchWorkspaceProjection",
    "RetouchWorkspaceStatus",
    "RevisionNotFound",
    "SOURCE_CODE_EXTENSIONS",
    "StoredBlob",
    "SystemArtifactLauncher",
    "TrustedDeliverableDeclaration",
    "minute_display_name",
    "MAX_RETOUCH_REFERENCES",
    "new_artifact_id",
    "new_revision_id",
    "PreparedArtifactAction",
    "sanitize_display_filename",
]
