"""Composition adapters joining independently testable EcoreX v1 domains."""

from .artifact_events import (
    ArtifactEventOutbox,
    ArtifactEventOutboxConflict,
    ArtifactEventOutboxError,
    ArtifactEventPublishTimeout,
    ArtifactEventOutboxSupervisor,
    ArtifactEventOutboxSupervisorSnapshot,
    ArtifactEventPublisher,
    OutboxRecord,
    RuntimeArtifactEventPublisher,
)
from .connector_events import RuntimeConnectorEventSink
from .connector_results import ArtifactReadRuntime, RuntimeConnectorResultCoordinator
from .image_orchestrator import ManagedImageRetouchAdapter
from .image_tools import (
    ImageGenerationToolHandler,
    ImageToolError,
    ImageToolPublicationBusy,
    ImageToolUnavailable,
    ImageVisionToolHandler,
    RuntimeImageToolBackend,
    production_pack_adapter_resolver,
)
from .managed_image import (
    ManagedImageClientError,
    ManagedImageDownloadedResult,
    ManagedImageInputAsset,
    ManagedImageJob,
    ManagedImageJobJournal,
    ManagedImageOrchestrationClient,
    ManagedImageResultDescriptor,
)
from .office_tools import OfficeSkillError, RuntimeOfficeSkillBackend
from .retouch import (
    RETOUCH_JOB_KIND,
    RetouchCoordinator,
    RetouchSnapshotContextProvider,
    RetouchSupervisorSnapshot,
    RetouchTurnAdmission,
    RetouchWorker,
    RetouchWorkerOutcome,
    RetouchWorkerResult,
    RetouchWorkerSupervisor,
    RuntimeRetouchBridge,
)
from .retouch_adapter import (
    CloudImageRetouchAdapter,
    RetouchAdapterError,
    RetouchImageAsset,
    RetouchMaskAsset,
    StructuredRetouchAdapterRequest,
    StructuredRetouchAdapterResult,
)
from .sandbox import (
    MacOSSandboxExecBackend,
    SandboxBackend,
    SandboxLaunchPlan,
    SandboxProbe,
    UnavailableSandboxBackend,
    WindowsAppContainerSandboxBackend,
)

__all__ = [
    "ArtifactEventOutbox",
    "ArtifactEventOutboxConflict",
    "ArtifactEventOutboxError",
    "ArtifactEventPublishTimeout",
    "ArtifactEventOutboxSupervisor",
    "ArtifactEventOutboxSupervisorSnapshot",
    "ArtifactEventPublisher",
    "OutboxRecord",
    "RuntimeArtifactEventPublisher",
    "RuntimeConnectorEventSink",
    "RuntimeConnectorResultCoordinator",
    "ArtifactReadRuntime",
    "CloudImageRetouchAdapter",
    "ManagedImageClientError",
    "ManagedImageDownloadedResult",
    "ManagedImageInputAsset",
    "ManagedImageJob",
    "ManagedImageJobJournal",
    "ManagedImageOrchestrationClient",
    "ManagedImageResultDescriptor",
    "ManagedImageRetouchAdapter",
    "OfficeSkillError",
    "ImageGenerationToolHandler",
    "ImageToolError",
    "ImageToolPublicationBusy",
    "ImageToolUnavailable",
    "ImageVisionToolHandler",
    "RuntimeImageToolBackend",
    "RuntimeOfficeSkillBackend",
    "production_pack_adapter_resolver",
    "RETOUCH_JOB_KIND",
    "RetouchAdapterError",
    "RetouchCoordinator",
    "RetouchSnapshotContextProvider",
    "RetouchImageAsset",
    "RetouchMaskAsset",
    "RetouchSupervisorSnapshot",
    "RetouchTurnAdmission",
    "RetouchWorker",
    "RetouchWorkerOutcome",
    "RetouchWorkerResult",
    "RetouchWorkerSupervisor",
    "RuntimeRetouchBridge",
    "StructuredRetouchAdapterRequest",
    "StructuredRetouchAdapterResult",
    "MacOSSandboxExecBackend",
    "SandboxBackend",
    "SandboxLaunchPlan",
    "SandboxProbe",
    "UnavailableSandboxBackend",
    "WindowsAppContainerSandboxBackend",
]
